name: Monthly Retraining Pipeline

on:
  # Runs at 02:00AM (UTC time), on 1 day of month . For Pakistan (UTC +5) at 7:00 AM
  schedule:
    - cron: "0 2 1 * *"

  # Testing
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

        # Testing - after push wait for 5 minutes 
      - name: Wait 5 minutes before retraining
        run: sleep 300

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

    #   # =========================
    #   # 1. Extract (NEW DATA)
    #   # =========================
    #   - name: Extract New Data
    #     run: python src/etl/extract.py

    #   # =========================
    #   # 2. Transform
    #   # =========================
    #   - name: Transform Data
    #     run: python src/etl/transform.py

      # =========================
      # 3. Train Model
      # =========================
      - name: Train Model
        run: python src/model/train.py
        env:
          PYTHONPATH: .